apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-service
  namespace: voicera-ai
  labels:
    app: voice-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voice-service
  template:
    metadata:
      labels:
        app: voice-service
        version: v1
    spec:
      containers:
      - name: voice-service
        image: voicera/voice-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: voicera-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: MONGO_URI
          value: "mongodb://admin:password@mongodb-service:27017/voicera_voice?authSource=admin"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: voicera-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: voicera-config
              key: REDIS_PORT
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: voicera-secrets
              key: groq-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: voice-service
  namespace: voicera-ai
  labels:
    app: voice-service
spec:
  selector:
    app: voice-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voice-service-hpa
  namespace: voicera-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voice-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
